import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('amad_diallo_stats.csv')
df['Date'] = pd.to_datetime(df['Date'])
df.sort_values('Date', inplace=True)
df.head()
df['Goals_per_90'] = df['Goals'] / (df['Minutes'] / 90)
df['Assists_per_90'] = df['Assists'] / (df['Minutes'] / 90)
df['xG_per_90'] = df['xG'] / (df['Minutes'] / 90)
df['xA_per_90'] = df['xA'] / (df['Minutes'] / 90)
df[['Date', 'Goals_per_90', 'Assists_per_90', 'xG_per_90', 'xA_per_90']].head()
plt.figure(figsize=(10, 5))
plt.plot(df['Date'], df['Goals_per_90'], label='Goals/90', marker='o')
plt.plot(df['Date'], df['Assists_per_90'], label='Assists/90', marker='s')
plt.plot(df['Date'], df['xG_per_90'], label='xG/90', linestyle='--', marker='^')
plt.plot(df['Date'], df['xA_per_90'], label='xA/90', linestyle='--', marker='d')
plt.title('Amad Diallo – Per 90 Performance Over Time')
plt.xlabel('Match Date')
plt.ylabel('Metric per 90 Minutes')
plt.xticks(rotation=45)
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()